### ISSUE TITLE
Enable skipping within tracks

### ISSUE THREAD

**Issue by rolandrohde** [pierrepoulpe/SqueezeboxQobuz#10]
Hi, 
please enable skipping within tracks. This requires some changes within the Plugin, and perhaps also in LMS? 

Thanks!

**Comment by mherger** [comment]
I think this issue has been discussed in length in the forums already. AFAIK LMS cannot skip within remote FLAC files. This can't be resolved in a plugin.

**Comment by rolandrohde** [comment]
Ok. I read the thread, andbsomebody there wanted to attempt it, but then never mentioned it again. So there was/is no way to tell whether it was actually attempted. 
But if it's a "hard" LMS limitation, then there is no point in trying.

**Comment by michaelherger** [comment]
Some user claims it was working with a minor code change. Will have to look into this:

http://forums.slimdevices.com/showthread.php?97146-Qobuz-com-streaming-plugin&p=880919&viewfull=1#post880919

**Comment by michaelherger** [comment]
This should now be available in the latest version.
