### ISSUE TITLE
Logging category added two times

### ISSUE THREAD

**Issue by ljungberg** [pierrepoulpe/SqueezeboxQobuz#13]
plugin.qobuz is added two times to the Log

(once in Plugin.pm with level  'ERROR' and once in Settings.pm with level 'INFO')

When looking at web GUI 'Settings'->'Advanced' choosing 'Logging' in drop down menu there is one entry for plugin.qobuz with level 'INFO'. I think the addLoggCategory call in Settings.pm overwrites the first one.

My guess is that you would want something like:

my $log = logger('plugin.qobuz');

in Settings.pm

**Comment by mherger** [comment]
Fixed in commit 4542094f765ee6d8cf213e4f00662c0740953bd1. Thanks!
