### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by marcoc1712** [pierrepoulpe/SqueezeboxQobuz#14]
Hi, the script SqueezeboxQobuz.user.js is not working anymore.

 I've hached a little and discovered it's becouse we need https, but then I got this error:

Mixed Content: The page at 'https://www.qobuz.com/ie-en/album/intavolatura-di-cimbalo-yoann-moulin/3770008056107' was loaded over HTTPS, but requested an insecure resource 'http://192.168.1.101:9000/status.html?p0=qobuz&p1=playalbum&p2=3770008056107'. This request has been blocked; the content must be served over HTTPS.

Where that request is issued? How could we mange to ask via https?

Thanks, Marco

**Comment by erdoukki** [comment]
Hi,
@marcoc1712 ;
thank you for the bug report, I have missed the https part.
I am looking on it and may propose a fix.

Regards,

**Comment by erdoukki** [comment]
It may be a difficult problem cause of xcross security check.
qobuz is in https and the http (no-ssl) access to the local Logitech Media Server cause a security fault which is blocked.
So I am still searching for a solution.

**Comment by erdoukki** [comment]
In the address bar at the right end should be a 'shield' icon, you can click on that to run insecure content.
Then the http:// content of your local network squeezebox server will be in warning mixed mode content and not in the error status, so it will work as usual before the add of the mixed content security awareness.

**Comment by erdoukki** [comment]
![desactivating protection](https://user-images.githubusercontent.com/2179472/39675444-75e0093c-515b-11e8-9e5f-42954a8be801.png)
![activating protection](https://user-images.githubusercontent.com/2179472/39675445-75f8f32a-515b-11e8-993c-0b52de907b63.png)
