### ISSUE TITLE
Plugin requesting a larger thumbnail than original

### ISSUE THREAD

**Issue by kayue** [pierrepoulpe/SqueezeboxQobuz#16]
I'm using the Qobuz plugin, and I noticed the image returning from image proxy is larger than the original one from Qobuz server.

Image proxy returning 1500px 

```
/imageproxy/https%3A%2F%2Fstatic.qobuz.com%2Fimages%2Fcovers%2F52%2F13%2F0094636981352_600.jpg/image.jpg
```

Original picture is 600px

```
https://static.qobuz.com/images/covers/52/13/0094636981352_600.jpg
```

Expected result would be something like this

```
/imageproxy/https%3A%2F%2Fstatic.qobuz.com%2Fimages%2Fcovers%2F52%2F13%2F0094636981352_600.jpg/image_300x300_f.png
```

**Comment by michaelherger** [comment]
Those first two images are absolutely identical when downloaded through my LMS. To the last bit identical. 

The last URL comes with resizing parameters, therefore it's scaled down to 300x300px instead of the original 600x600px.
