### ISSUE TITLE
New Hi-Res formats for 24 bit =< 96kHz

### ISSUE THREAD

**Issue by kayue** [pierrepoulpe/SqueezeboxQobuz#18]
Qobuz offers different Hi-Res formats. A new one is `format_id=7` for FLAC Hi-Res 24 bit =< 96kHz.
It is an important option for Pi user because 24/192 is not well supported in Pi due to internet or usb bandwidth. 

- Documentation: https://github.com/Qobuz/api-documentation/blob/master/endpoints/track/getFileUrl.md#parameters
- Related file: https://github.com/pierrepoulpe/SqueezeboxQobuz/blob/0b97fef21fad02f09a79a93fd8b7235fa91b3e06/API.pm#L23-L25

Thanks

**Comment by michaelherger** [comment]
Are you saying this is important because you want to be able to limit the quality for some players?

**Comment by kayue** [comment]
@michaelherger Yes. 24/192 is huge in file size and could be laggy for some people due to internet bandwidth. Not all DAC support such high resolution too. In fact 24/96 is the limit of TOSLink.

If I remember correctly it is a new option for Qobuz's official app too. Before there was only Flac and Hires (24/192).

![Qobuz](https://user-images.githubusercontent.com/193112/57126553-eb936f80-6dbf-11e9-8340-3509e5fa01bf.png)
