### ISSUE TITLE
Can i use PicorePlayer without an LMS?

### ISSUE THREAD

**Issue by 9acca9** [pierrepoulpe/SqueezeboxQobuz#26]
Hi, i just want PicorePlayer to use with Qobuz, i dont have an LMS. So, is possible to use it like that?
Thanks.

ps.:i dont find info related to how acomplish that, i just find things with LMS.

**Comment by michaelherger** [comment]
No. piCorePlayer won't work without LMS. And this Qobuz implementation is a plugin for LMS.
