### ISSUE TITLE
media scan details numbers

### ISSUE THREAD

**Issue by th2j** [pierrepoulpe/SqueezeboxQobuz#28]
Hello

when i rescan my qobuz library, the media scan details shows a number of albums and playlists that is higher than reality (2 more).

does it comes from the "+2" in the file Importer.pm ?

$progress->total(scalar @$albums + 2);
$progress->total((scalar @$playlists) + 2);

Thanks
Thomas

**Comment by michaelherger** [comment]
Yeah, don't really remember why I did that... I'll look into that, thanks!
