### ISSUE TITLE
Multi user support

### ISSUE THREAD

**Issue by bjarteskogoy** [pierrepoulpe/SqueezeboxQobuz#62]
The Tidal-plugin supports adding multiple Tidal accounts and selecting a Tidal-account per player.
Has this been considered for the Qobuz-plugin? In a house with a lot of SqueezeBoxes and five users it is a valuable advantage.

**Comment by michaelherger** [comment]
Yes, the topic has come up before. But it'll be quite a bit of work to implement. More than I can invest at this point...

**Comment by michaelherger** [comment]
It's coming! https://github.com/pierrepoulpe/SqueezeboxQobuz/pull/65
