### ISSUE TITLE
Not an issue - more a request

### ISSUE THREAD

**Issue by JosefAschauer** [pierrepoulpe/SqueezeboxQobuz#69]
Since mysqueezebox servers are being shut down in Feb 2024, there will be no Tidal plugin anymore since it handles the authentication via mysqueezebox.com.
I guess the community demand on such a plugin is enormous, at least from what I read. 
Since you've done an excellent job on the Qobuz addin - would it be possible for you to write a Tidal addin as well? Maybe the Kodi / Plex plugin for Tidal, also written in Pyton, is a good start - if you are interested

**Comment by michaelherger** [comment]
Hi there - the implementation of a Deezer or TIDAL plugin is more of a legal issue than a technical/implementation challenge. If I had all the permissions we'd need we'd quickly be able to come up with something. But that's not in our power.

**Comment by JosefAschauer** [comment]
Thanks for your reply. Is Tidal actively blocking this, have you reached out to them already? Anything I could do to support this?

Best,
Josef

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michaelherger** [comment]
Please see our community forum... in particular eg. https://forums.slimdevices.com/forum/user-forums/general-discussion/1668568-tidal-deezer-pandora

**Comment by JosefAschauer** [comment]
Thanks! Thats what I wrote to Tidal:

Hi,
My whole audio experiene at home is build upon logitech media server and i use the tidal plugin (mysqueezebox.com) to listen to tidal. Mysqueezebox.com (logitech) is discontinued starting February, which means that Tidal will stop working for me then. I am kindly asking you to elaborate a solution with the slimdevices community to find an alternative. Thousands of users will be affected otherwise. Since Qobuz supports LMS as a standalone plugin, i am asking you to do the same as i want to continue my subscription with you.

Kind regards,
AS

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JosefAschauer** [comment]
Hi,

Seems Tidal did it😊
https://github.com/orgs/tidal-music/discussions

An API of theirs is publicly available now
