### ISSUE TITLE
Support new Playlists

### ISSUE THREAD

**Issue by rolandrohde** [pierrepoulpe/SqueezeboxQobuz#9]
Hi, 

There was a change to the Qobuz API and the nethod for getting Playlists changed from "getPublicPlaylists" to "getFeatured" 
Can you implement this in the Plugin please?

Thanks!

**Comment by michaelherger** [comment]
This happened long ago... thanks!

**Comment by michaelherger** [comment]
for the records: commit aa53442a73df3ae2ed6276e8dfa2a60a368eee6e
